# Generated by Django 3.2.13 on 2022-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
