# Generated by Django 3.2.13 on 2022-05-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_alter_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
