# Generated by Django 3.2.13 on 2022-05-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_auto_20220518_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tpost',
        ),
    ]
