# Generated by Django 3.2.13 on 2022-05-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_rename_tpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
