# Generated by Django 4.0.3 on 2022-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0015_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
