# Generated by Django 4.0.3 on 2022-05-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0019_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
