# Generated by Django 4.0.3 on 2022-05-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0022_like_user_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
