# Generated by Django 4.0.3 on 2022-05-22 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new', '0028_likexx_delete_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likexx',
            new_name='Like',
        ),
    ]
