# Generated by Django 4.0.3 on 2022-05-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0029_rename_likexx_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
