# Generated by Django 4.0.3 on 2022-05-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0034_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
